const cow = {
    name: 'Cow',
    base_image: '/assets/cow/Head__Legs.png',
    meat_parts: [
        {
            name: 'Briskit',
            image: '/assets/cow/Brisket.png',
            top: 174,
            left: 156,
            price: 20.00,
        },
        {
            name: 'Neck',
            image: '/assets/cow/Neck.png',
            top: 15,
            left: 97,
            price: 15.00,
        },
        {
            name: 'Chuck',
            image: '/assets/cow/Chuck.png',
            top: 16,
            left: 168,
            price: 23.00,
        },
        {
            name: 'Shank Front',
            image: '/assets/cow/Shank_1.png',
            top: 151,
            left: 188,
            price: 9.99,
        },
        {
            name: 'Rib',
            image: '/assets/cow/Rib.png',
            top: 23,
            left: 263,
            price: 25.00,
        },
        {
            name: 'Short Plate',
            image: '/assets/cow/Short_Plate.png',
            top: 150,
            left: 259,
            price: 15.00,
        },
        {
            name: 'Short Loin',
            image: '/assets/cow/Short_Loin.png',
            top: 23,
            left: 358,
            price: 30.00,
        },
        {
            name: 'Flank',
            image: '/assets/cow/Flank.png',
            top: 148,
            left: 364,
            price: 15.00,
        },
        {
            name: 'Sirloin',
            image: '/assets/cow/Sirloin.png',
            top: 23,
            left: 435,
            price: 25.00,
        },
        {
            name: 'Tenderloin',
            image: '/assets/cow/Tenderloin.png',
            top: 53,
            left: 368,
            price: 30.00,
        },
        {
            name: 'Top Sirloin',
            image: '/assets/cow/Top_Sirloin_1.png',
            top: 85,
            left: 426,
            price: 25.00,
        },
        {
            name: 'Bottom Sirloin',
            image: '/assets/cow/Bottom_Sirloin.png',
            top: 109,
            left: 424,
            price: 25.00,
        },
        {
            name: 'Rump',
            image: '/assets/cow/Rump.png',
            top: 23,
            left: 496,
            price: 25.00,
        },
        {
            name: 'Round',
            image: '/assets/cow/Round.png',
            top: 76,
            left: 477,
            price: 25.00,
        },
        {
            name: 'Shank Back',
            image: '/assets/cow/Shank.png',
            top: 164,
            left: 514,
            price: 9.99,
        },
        {
            name: 'Ox Tail',
            image: '/assets/cow/Ox_Tail.png',
            top: 28,
            left: 543,
            price: 9.99,
        }
    ]
}

module.exports = cow;